### ISSUE TITLE
Remove deprecated '~' from @import statements

### ISSUE THREAD

**Issue by b-lackner** [palmetto/palmetto-components#619] opened 2021-10-18 23:39 UTC
From sass-loader(https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules): 
"tilde '~' imports are deprecated and is recommended to be removed."
These import statements are also complicating the process of importing Palmetto components into the Mapdwell repository. If possible, these should be removed, at least from the module.scss files.

**Comment by juanfabrega** [comment] 2021-11-09 16:14
Hey @b-lackner after updating to the latest version of storybook, I've confirmed that it is still on webpack 4, which in turn is still using an older version of sass-loader, which doesn't support removing this to properly resolve imports. At this time it looks like we aren't ready to move away from these so I will close this issue until we're at a point where the build chain is is getting another overhaul.

**Closed by juanfabrega** 2021-11-09 16:14 UTC
